Traceback (most recent call last):
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\barguzin\Anaconda3\envs\geo_env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cenpy 
dectest = cenpy.products.Decennial2010()
gol_data = dectest.from_place('Goleta,CA', level='block', variables=['^P004', 'P001001'])

fig, ax = plt.subplots(figsize=(12,4))

gol_data.plot(column='P004003', cmap='Reds', ax=ax, fc='w', ec='k');
gol_data.plot(ax=ax, fc='None', ec='k');
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [16], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mcenpy[39;00m 
[0;32m      2[0m dectest [38;5;241m=[39m cenpy[38;5;241m.[39mproducts[38;5;241m.[39mDecennial2010()
[0;32m      3[0m gol_data [38;5;241m=[39m dectest[38;5;241m.[39mfrom_place([38;5;124m'[39m[38;5;124mGoleta,CA[39m[38;5;124m'[39m, level[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblock[39m[38;5;124m'[39m, variables[38;5;241m=[39m[[38;5;124m'[39m[38;5;124m^P004[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mP001001[39m[38;5;124m'[39m])

[1;31mModuleNotFoundError[0m: No module named 'cenpy'
ModuleNotFoundError: No module named 'cenpy'

